rm(list=ls())

library(dplyr)
library(tidyverse)

mdis <- read.table("~/Google/R_Jaesol/보육요양 조사자료/요양기관_2019.csv", header=FALSE, sep=",", colClasses = c("character"
                                                                                                        , "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "numeric", "numeric", "numeric", "numeric", "numeric"
                                                                                                        , "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"
                                                                                                        , "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"
                                                                                                        , "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"
                                                                                                        , "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"
                                                                                                        , "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"
                                                                                                        , "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"
                                                                                                        , "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"
                                                                                                        , "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "character", "character", "character", "character", "character", "character"
                                                                                                        , "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "character", "character", "character", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "character", "numeric"
                                                                                                        , "numeric", "numeric", "numeric", "numeric", "numeric", "character", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "character", "character", "character", "character", "character", "character", "character"
                                                                                                        , "character", "character", "character", "character", "character", "character", "character", "numeric", "numeric", "numeric", "numeric", "character", "numeric", "numeric", "numeric", "character", "numeric", "numeric", "numeric", "character"
                                                                                                        , "numeric", "numeric", "numeric", "character", "numeric", "numeric", "numeric", "character", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "character", "character", "numeric", "character"
                                                                                                        , "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "character", "character", "character"
                                                                                                        , "character", "character", "character", "character", "character", "numeric", "character", "character", "character", "character", "character", "character", "character", "character", "character", "numeric", "numeric", "numeric"), skip=1, na.string=c("*","**","***","****","*****","******","*******","********","*********","**********","."))

mdis$V1<- recode_factor(mdis$V1, '1'="대도시")
mdis$V1<- recode_factor(mdis$V1, '2'="중소도시")
mdis$V1<- recode_factor(mdis$V1, '3'="농어촌")
mdis$V2<- recode_factor(mdis$V2, '1'="방문요양")
mdis$V2<- recode_factor(mdis$V2, '2'="방문목욕")
mdis$V2<- recode_factor(mdis$V2, '3'="방문간호")
mdis$V2<- recode_factor(mdis$V2, '4'="주야간보호")
mdis$V2<- recode_factor(mdis$V2, '5'="단기보호")
mdis$V2<- recode_factor(mdis$V2, '6'="노인요양공동생활가정(9명 이하)")
mdis$V2<- recode_factor(mdis$V2, '7'="노인요양시설(10~29명)")
mdis$V2<- recode_factor(mdis$V2, '8'="노인요양시설(30~49명)")
mdis$V2<- recode_factor(mdis$V2, '9'="노인요양시설(50명 이상)")
mdis$V3<- recode_factor(mdis$V3, '1'="주거지역")
mdis$V3<- recode_factor(mdis$V3, '2'="상업·업무지역")
mdis$V3<- recode_factor(mdis$V3, '3'="농어촌지역")
mdis$V3<- recode_factor(mdis$V3, '4'="산지지역")
mdis$V3<- recode_factor(mdis$V3, '5'="기타")
mdis$V4<- recode_factor(mdis$V4, '1'="20분 이내")
mdis$V4<- recode_factor(mdis$V4, '2'="21분~30분")
mdis$V4<- recode_factor(mdis$V4, '3'="31분~40분")
mdis$V4<- recode_factor(mdis$V4, '4'="41분 이상")
mdis$V5<- recode_factor(mdis$V5, '1'="개인")
mdis$V5<- recode_factor(mdis$V5, '2'="영리법인")
mdis$V5<- recode_factor(mdis$V5, '3'="사회복지법인")
mdis$V5<- recode_factor(mdis$V5, '4'="종교법인")
mdis$V5<- recode_factor(mdis$V5, '5'="학교법인")
mdis$V5<- recode_factor(mdis$V5, '6'="의료법인")
mdis$V5<- recode_factor(mdis$V5, '7'="그외 비영리법인")
mdis$V5<- recode_factor(mdis$V5, '8'="국가 및 지방자치단체")
mdis$V5<- recode_factor(mdis$V5, '9'="기타")
mdis$V6<- recode_factor(mdis$V6, '1'="단독")
mdis$V6<- recode_factor(mdis$V6, '2'="병설")
mdis$V7<- recode_factor(mdis$V7, '1'="장기요양기관과 병설")
mdis$V7<- recode_factor(mdis$V7, '2'="장기요양기관 이외 사회복지시설과 병설")
mdis$V7<- recode_factor(mdis$V7, '3'="의료기관과 병설")
mdis$V7<- recode_factor(mdis$V7, '4'="기타")
mdis$V8<- recode_factor(mdis$V8, '1'="예")
mdis$V8<- recode_factor(mdis$V8, '2'="아니오")
mdis$V9<- recode_factor(mdis$V9, '1'="예")
mdis$V9<- recode_factor(mdis$V9, '2'="아니오")
mdis$V10<- recode_factor(mdis$V10, '1'="예")
mdis$V10<- recode_factor(mdis$V10, '2'="아니오")
mdis$V11<- recode_factor(mdis$V11, '1'="예")
mdis$V11<- recode_factor(mdis$V11, '2'="아니오")
mdis$V12<- recode_factor(mdis$V12, '1'="예")
mdis$V12<- recode_factor(mdis$V12, '2'="아니오")
mdis$V13<- recode_factor(mdis$V13, '1'="예")
mdis$V13<- recode_factor(mdis$V13, '2'="아니오")
mdis$V14<- recode_factor(mdis$V14, '1'="예")
mdis$V14<- recode_factor(mdis$V14, '2'="아니오")
mdis$V15<- recode_factor(mdis$V15, '1'="개인 소유")
mdis$V15<- recode_factor(mdis$V15, '2'="법인 소유")
mdis$V15<- recode_factor(mdis$V15, '3'="국가 또는 지방자치단체 소유")
mdis$V15<- recode_factor(mdis$V15, '4'="전세")
mdis$V15<- recode_factor(mdis$V15, '5'="월세")
mdis$V15<- recode_factor(mdis$V15, '6'="기타")
mdis$V16<- recode_factor(mdis$V16, '1'="없음")
mdis$V16<- recode_factor(mdis$V16, '2'="10% 이하")
mdis$V16<- recode_factor(mdis$V16, '3'="10% 초과~20% 이하")
mdis$V16<- recode_factor(mdis$V16, '4'="20% 초과~30% 이하")
mdis$V16<- recode_factor(mdis$V16, '5'="30% 초과~40% 이하")
mdis$V16<- recode_factor(mdis$V16, '6'="40% 초과~50% 이하")
mdis$V16<- recode_factor(mdis$V16, '7'="50% 초과~60% 이하")
mdis$V16<- recode_factor(mdis$V16, '8'="60% 초과~70% 이하")
mdis$V16<- recode_factor(mdis$V16, '9'="70% 초과~80% 이하")
mdis$V176<- recode_factor(mdis$V176, '1'="매우 필요하다")
mdis$V176<- recode_factor(mdis$V176, '2'="필요하다")
mdis$V176<- recode_factor(mdis$V176, '3'="보통이다")
mdis$V176<- recode_factor(mdis$V176, '4'="필요하지 않다")
mdis$V176<- recode_factor(mdis$V176, '5'="전혀 필요하지 않다")
mdis$V177<- recode_factor(mdis$V177, '1'="시설장")
mdis$V177<- recode_factor(mdis$V177, '2'="사무국장")
mdis$V177<- recode_factor(mdis$V177, '3'="사회복지사")
mdis$V177<- recode_factor(mdis$V177, '4'="간호(조무)사")
mdis$V177<- recode_factor(mdis$V177, '5'="물리(작업)치료사")
mdis$V177<- recode_factor(mdis$V177, '6'="요양보호사")
mdis$V177<- recode_factor(mdis$V177, '7'="기타")
mdis$V178<- recode_factor(mdis$V178, '1'="시설장")
mdis$V178<- recode_factor(mdis$V178, '2'="사무국장")
mdis$V178<- recode_factor(mdis$V178, '3'="사회복지사")
mdis$V178<- recode_factor(mdis$V178, '4'="간호(조무)사")
mdis$V178<- recode_factor(mdis$V178, '5'="물리(작업)치료사")
mdis$V178<- recode_factor(mdis$V178, '6'="요양보호사")
mdis$V178<- recode_factor(mdis$V178, '7'="기타")
mdis$V179<- recode_factor(mdis$V179, '1'="교육 시간/내용 등 개선")
mdis$V179<- recode_factor(mdis$V179, '10'="기타")
mdis$V179<- recode_factor(mdis$V179, '2'="치매전문교육 포함")
mdis$V179<- recode_factor(mdis$V179, '3'="직무교육의 의무화")
mdis$V179<- recode_factor(mdis$V179, '4'="실무 중심의 교육내용 개편")
mdis$V179<- recode_factor(mdis$V179, '5'="양질의 전문강사 야성")
mdis$V179<- recode_factor(mdis$V179, '6'="요양보호사 이외 직종에 대한 전문교육 제공")
mdis$V179<- recode_factor(mdis$V179, '7'="근무시간으로 인정하는 교육 범위/시간 확대")
mdis$V179<- recode_factor(mdis$V179, '8'="교육 시간대 다양화")
mdis$V179<- recode_factor(mdis$V179, '9'="교육장소의 접근성 확대")
mdis$V180<- recode_factor(mdis$V180, '1'="교육 시간/내용 등 개선")
mdis$V180<- recode_factor(mdis$V180, '10'="기타")
mdis$V180<- recode_factor(mdis$V180, '2'="치매전문교육 포함")
mdis$V180<- recode_factor(mdis$V180, '3'="직무교육의 의무화")
mdis$V180<- recode_factor(mdis$V180, '4'="실무 중심의 교육내용 개편")
mdis$V180<- recode_factor(mdis$V180, '5'="양질의 전문강사 야성")
mdis$V180<- recode_factor(mdis$V180, '6'="요양보호사 이외 직종에 대한 전문교육 제공")
mdis$V180<- recode_factor(mdis$V180, '7'="근무시간으로 인정하는 교육 범위/시간 확대")
mdis$V180<- recode_factor(mdis$V180, '8'="교육 시간대 다양화")
mdis$V180<- recode_factor(mdis$V180, '9'="교육장소의 접근성 확대")
mdis$V181<- recode_factor(mdis$V181, '1'="예")
mdis$V181<- recode_factor(mdis$V181, '2'="아니오")
mdis$V188<- recode_factor(mdis$V188, '1'="직원의 치매전문교육 참여에 따른 인력공백 및 대체 인력수급 어려움")
mdis$V188<- recode_factor(mdis$V188, '2'="치매전담실 운영에 따른 추가적인 행정부담")
mdis$V188<- recode_factor(mdis$V188, '3'="치매전담실 이용노인 모집의 불확실성")
mdis$V188<- recode_factor(mdis$V188, '4'="경영수지에 맞지 않음")
mdis$V188<- recode_factor(mdis$V188, '5'="치매전담실 시설요건 충족의 어려움")
mdis$V188<- recode_factor(mdis$V188, '6'="치매전문교육을 받은 요양보호사 채용의 어려움")
mdis$V188<- recode_factor(mdis$V188, '7'="기타")
mdis$V189<- recode_factor(mdis$V189, '1'="예")
mdis$V189<- recode_factor(mdis$V189, '2'="아니오")
mdis$V190<- recode_factor(mdis$V190, '1'="있다")
mdis$V190<- recode_factor(mdis$V190, '2'="없다")
mdis$V200<- recode_factor(mdis$V200, '1'="있다")
mdis$V200<- recode_factor(mdis$V200, '2'="없다")
mdis$V207<- recode_factor(mdis$V207, '1'="있다")
mdis$V207<- recode_factor(mdis$V207, '2'="없다")
mdis$V215<- recode_factor(mdis$V215, '1'="매우 어렵다")
mdis$V215<- recode_factor(mdis$V215, '2'="어렵다")
mdis$V215<- recode_factor(mdis$V215, '3'="보통이다")
mdis$V215<- recode_factor(mdis$V215, '4'="어렵지 않다")
mdis$V215<- recode_factor(mdis$V215, '5'="전혀 어렵지 않다")
mdis$V215<- recode_factor(mdis$V215, '6'="해당없음")
mdis$V216<- recode_factor(mdis$V216, '1'="매우 어렵다")
mdis$V216<- recode_factor(mdis$V216, '2'="어렵다")
mdis$V216<- recode_factor(mdis$V216, '3'="보통이다")
mdis$V216<- recode_factor(mdis$V216, '4'="어렵지 않다")
mdis$V216<- recode_factor(mdis$V216, '5'="전혀 어렵지 않다")
mdis$V216<- recode_factor(mdis$V216, '6'="해당없음")
mdis$V217<- recode_factor(mdis$V217, '1'="매우 어렵다")
mdis$V217<- recode_factor(mdis$V217, '2'="어렵다")
mdis$V217<- recode_factor(mdis$V217, '3'="보통이다")
mdis$V217<- recode_factor(mdis$V217, '4'="어렵지 않다")
mdis$V217<- recode_factor(mdis$V217, '5'="전혀 어렵지 않다")
mdis$V217<- recode_factor(mdis$V217, '6'="해당없음")
mdis$V218<- recode_factor(mdis$V218, '1'="매우 어렵다")
mdis$V218<- recode_factor(mdis$V218, '2'="어렵다")
mdis$V218<- recode_factor(mdis$V218, '3'="보통이다")
mdis$V218<- recode_factor(mdis$V218, '4'="어렵지 않다")
mdis$V218<- recode_factor(mdis$V218, '5'="전혀 어렵지 않다")
mdis$V218<- recode_factor(mdis$V218, '6'="해당없음")
mdis$V219<- recode_factor(mdis$V219, '1'="매우 어렵다")
mdis$V219<- recode_factor(mdis$V219, '2'="어렵다")
mdis$V219<- recode_factor(mdis$V219, '3'="보통이다")
mdis$V219<- recode_factor(mdis$V219, '4'="어렵지 않다")
mdis$V219<- recode_factor(mdis$V219, '5'="전혀 어렵지 않다")
mdis$V219<- recode_factor(mdis$V219, '6'="해당없음")
mdis$V220<- recode_factor(mdis$V220, '1'="매우 어렵다")
mdis$V220<- recode_factor(mdis$V220, '2'="어렵다")
mdis$V220<- recode_factor(mdis$V220, '3'="보통이다")
mdis$V220<- recode_factor(mdis$V220, '4'="어렵지 않다")
mdis$V220<- recode_factor(mdis$V220, '5'="전혀 어렵지 않다")
mdis$V220<- recode_factor(mdis$V220, '6'="해당없음")
mdis$V221<- recode_factor(mdis$V221, '1'="매우 어렵다")
mdis$V221<- recode_factor(mdis$V221, '2'="어렵다")
mdis$V221<- recode_factor(mdis$V221, '3'="보통이다")
mdis$V221<- recode_factor(mdis$V221, '4'="어렵지 않다")
mdis$V221<- recode_factor(mdis$V221, '5'="전혀 어렵지 않다")
mdis$V221<- recode_factor(mdis$V221, '6'="해당없음")
mdis$V222<- recode_factor(mdis$V222, '1'="매우 어렵다")
mdis$V222<- recode_factor(mdis$V222, '2'="어렵다")
mdis$V222<- recode_factor(mdis$V222, '3'="보통이다")
mdis$V222<- recode_factor(mdis$V222, '4'="어렵지 않다")
mdis$V222<- recode_factor(mdis$V222, '5'="전혀 어렵지 않다")
mdis$V222<- recode_factor(mdis$V222, '6'="해당없음")
mdis$V223<- recode_factor(mdis$V223, '1'="매우 어렵다")
mdis$V223<- recode_factor(mdis$V223, '2'="어렵다")
mdis$V223<- recode_factor(mdis$V223, '3'="보통이다")
mdis$V223<- recode_factor(mdis$V223, '4'="어렵지 않다")
mdis$V223<- recode_factor(mdis$V223, '5'="전혀 어렵지 않다")
mdis$V223<- recode_factor(mdis$V223, '6'="해당없음")
mdis$V224<- recode_factor(mdis$V224, '1'="매우 어렵다")
mdis$V224<- recode_factor(mdis$V224, '2'="어렵다")
mdis$V224<- recode_factor(mdis$V224, '3'="보통이다")
mdis$V224<- recode_factor(mdis$V224, '4'="어렵지 않다")
mdis$V224<- recode_factor(mdis$V224, '5'="전혀 어렵지 않다")
mdis$V224<- recode_factor(mdis$V224, '6'="해당없음")
mdis$V225<- recode_factor(mdis$V225, '1'="지역 내 장기요양 인정자의 부족")
mdis$V225<- recode_factor(mdis$V225, '2'="장기요양 인정자의 요양병원 이용")
mdis$V225<- recode_factor(mdis$V225, '3'="장기요양급여를 이용하지 않음")
mdis$V225<- recode_factor(mdis$V225, '4'="장기요양기관의 과잉 경쟁")
mdis$V225<- recode_factor(mdis$V225, '5'="해당기관에서 제공하지 않는 급여 선호")
mdis$V225<- recode_factor(mdis$V225, '6'="기타")
mdis$V226<- recode_factor(mdis$V226, '1'="지역 내 장기요양 인정자의 부족")
mdis$V226<- recode_factor(mdis$V226, '2'="장기요양 인정자의 요양병원 이용")
mdis$V226<- recode_factor(mdis$V226, '3'="장기요양급여를 이용하지 않음")
mdis$V226<- recode_factor(mdis$V226, '4'="장기요양기관의 과잉 경쟁")
mdis$V226<- recode_factor(mdis$V226, '5'="해당기관에서 제공하지 않는 급여 선호")
mdis$V226<- recode_factor(mdis$V226, '6'="기타")
mdis$V227<- recode_factor(mdis$V227, '1'="예")
mdis$V227<- recode_factor(mdis$V227, '2'="아니오")
mdis$V228<- recode_factor(mdis$V228, '1'="주거용 건물 전체 또는 일부 공간")
mdis$V228<- recode_factor(mdis$V228, '2'="공공기관, 복지기관, 장기요양기관 등의 일부 공간")
mdis$V228<- recode_factor(mdis$V228, '3'="상가 또는 업무용 건물의 일부 공간")
mdis$V228<- recode_factor(mdis$V228, '4'="병원 등 의료시설의 일부 공간")
mdis$V228<- recode_factor(mdis$V228, '5'="타용도 건물을 용도 변경하여 단독으로 사용")
mdis$V228<- recode_factor(mdis$V228, '6'="기타")
mdis$V233<- recode_factor(mdis$V233, '1'="있다")
mdis$V233<- recode_factor(mdis$V233, '2'="없다")
mdis$V233<- recode_factor(mdis$V233, '3'="해당없음")
mdis$V237<- recode_factor(mdis$V237, '1'="있다")
mdis$V237<- recode_factor(mdis$V237, '2'="없다")
mdis$V237<- recode_factor(mdis$V237, '3'="해당없음")
mdis$V241<- recode_factor(mdis$V241, '1'="있다")
mdis$V241<- recode_factor(mdis$V241, '2'="없다")
mdis$V241<- recode_factor(mdis$V241, '3'="해당없음")
mdis$V245<- recode_factor(mdis$V245, '1'="있다")
mdis$V245<- recode_factor(mdis$V245, '2'="없다")
mdis$V245<- recode_factor(mdis$V245, '3'="해당없음")
mdis$V249<- recode_factor(mdis$V249, '1'="있다")
mdis$V249<- recode_factor(mdis$V249, '2'="없다")
mdis$V249<- recode_factor(mdis$V249, '3'="해당없음")
mdis$V258<- recode_factor(mdis$V258, '1'="24시간 근무 + 2일 휴무")
mdis$V258<- recode_factor(mdis$V258, '2'="24시간 격일제")
mdis$V258<- recode_factor(mdis$V258, '3'="2교대")
mdis$V258<- recode_factor(mdis$V258, '4'="3교대")
mdis$V258<- recode_factor(mdis$V258, '5'="4교대")
mdis$V258<- recode_factor(mdis$V258, '6'="주간 근무자와 야간 근무자 별도 채용")
mdis$V258<- recode_factor(mdis$V258, '7'="기타")
mdis$V259<- recode_factor(mdis$V259, '1'="교대제")
mdis$V259<- recode_factor(mdis$V259, '2'="야간전담 근무자")
mdis$V259<- recode_factor(mdis$V259, '3'="교대제+야간전담 근무자")
mdis$V259<- recode_factor(mdis$V259, '4'="기타")
mdis$V261<- recode_factor(mdis$V261, '1'="예")
mdis$V261<- recode_factor(mdis$V261, '2'="아니오")
mdis$V279<- recode_factor(mdis$V279, '1'="예")
mdis$V279<- recode_factor(mdis$V279, '2'="아니오")
mdis$V280<- recode_factor(mdis$V280, '1'="예")
mdis$V280<- recode_factor(mdis$V280, '2'="아니오")
mdis$V281<- recode_factor(mdis$V281, '1'="예")
mdis$V281<- recode_factor(mdis$V281, '2'="아니오")
mdis$V282<- recode_factor(mdis$V282, '1'="예")
mdis$V282<- recode_factor(mdis$V282, '2'="아니오")
mdis$V283<- recode_factor(mdis$V283, '1'="예")
mdis$V283<- recode_factor(mdis$V283, '2'="아니오")
mdis$V284<- recode_factor(mdis$V284, '1'="예")
mdis$V284<- recode_factor(mdis$V284, '2'="아니오")
mdis$V285<- recode_factor(mdis$V285, '1'="예")
mdis$V285<- recode_factor(mdis$V285, '2'="아니오")
mdis$V286<- recode_factor(mdis$V286, '1'="남자")
mdis$V286<- recode_factor(mdis$V286, '2'="여자")
mdis$V288<- recode_factor(mdis$V288, '1'="사회복지사")
mdis$V288<- recode_factor(mdis$V288, '2'="의사")
mdis$V288<- recode_factor(mdis$V288, '3'="치과의사")
mdis$V288<- recode_factor(mdis$V288, '4'="한의사")
mdis$V288<- recode_factor(mdis$V288, '5'="간호사")
mdis$V288<- recode_factor(mdis$V288, '6'="간호조무사")
mdis$V288<- recode_factor(mdis$V288, '7'="요양보호사")
mdis$V289<- recode_factor(mdis$V289, '1'="사회복지사")
mdis$V289<- recode_factor(mdis$V289, '2'="의사")
mdis$V289<- recode_factor(mdis$V289, '3'="치과의사")
mdis$V289<- recode_factor(mdis$V289, '4'="한의사")
mdis$V289<- recode_factor(mdis$V289, '5'="간호사")
mdis$V289<- recode_factor(mdis$V289, '6'="간호조무사")
mdis$V289<- recode_factor(mdis$V289, '7'="요양보호사")
mdis$V290<- recode_factor(mdis$V290, '1'="사회복지사")
mdis$V290<- recode_factor(mdis$V290, '2'="의사")
mdis$V290<- recode_factor(mdis$V290, '3'="치과의사")
mdis$V290<- recode_factor(mdis$V290, '4'="한의사")
mdis$V290<- recode_factor(mdis$V290, '5'="간호사")
mdis$V290<- recode_factor(mdis$V290, '6'="간호조무사")
mdis$V290<- recode_factor(mdis$V290, '7'="요양보호사")
mdis$V291<- recode_factor(mdis$V291, '1'="사회복지사")
mdis$V291<- recode_factor(mdis$V291, '2'="의사")
mdis$V291<- recode_factor(mdis$V291, '3'="치과의사")
mdis$V291<- recode_factor(mdis$V291, '4'="한의사")
mdis$V291<- recode_factor(mdis$V291, '5'="간호사")
mdis$V291<- recode_factor(mdis$V291, '6'="간호조무사")
mdis$V291<- recode_factor(mdis$V291, '7'="요양보호사")
mdis$V292<- recode_factor(mdis$V292, '1'="사회복지사")
mdis$V292<- recode_factor(mdis$V292, '2'="의사")
mdis$V292<- recode_factor(mdis$V292, '3'="치과의사")
mdis$V292<- recode_factor(mdis$V292, '4'="한의사")
mdis$V292<- recode_factor(mdis$V292, '5'="간호사")
mdis$V292<- recode_factor(mdis$V292, '6'="간호조무사")
mdis$V292<- recode_factor(mdis$V292, '7'="요양보호사")
mdis$V293<- recode_factor(mdis$V293, '1'="사회복지사")
mdis$V293<- recode_factor(mdis$V293, '2'="의사")
mdis$V293<- recode_factor(mdis$V293, '3'="치과의사")
mdis$V293<- recode_factor(mdis$V293, '4'="한의사")
mdis$V293<- recode_factor(mdis$V293, '5'="간호사")
mdis$V293<- recode_factor(mdis$V293, '6'="간호조무사")
mdis$V293<- recode_factor(mdis$V293, '7'="요양보호사")
mdis$V294<- recode_factor(mdis$V294, '1'="사회복지사")
mdis$V294<- recode_factor(mdis$V294, '2'="의사")
mdis$V294<- recode_factor(mdis$V294, '3'="치과의사")
mdis$V294<- recode_factor(mdis$V294, '4'="한의사")
mdis$V294<- recode_factor(mdis$V294, '5'="간호사")
mdis$V294<- recode_factor(mdis$V294, '6'="간호조무사")
mdis$V294<- recode_factor(mdis$V294, '7'="요양보호사")

colnames(mdis) = c("지역구분"
                   , "제공 급여유형", "기관위치", "조사소요시간", "1. 운영주체", "2. 단독 및 병설 여부", "2-1. 병설형태", "2-2. 급여유형 제공 여부_방문요양", "2-2. 급여유형 제공 여부_방문목욕", "2-2. 급여유형 제공 여부_방문간호", "2-2. 급여유형 제공 여부_주야간보호", "2-2. 급여유형 제공 여부_단기보호", "2-2. 급여유형 제공 여부_노인요양공동생활가정", "2-2. 급여유형 제공 여부_노인요양시설", "3. 건물 점유형태", "3-1. 저당권 금액 비율", "4. 기관 이용자의 현황_총계", "4. 기관 이용자의 현황_1등급", "4. 기관 이용자의 현황_2등급", "4. 기관 이용자의 현황_3등급", "4. 기관 이용자의 현황_4등급"
                   , "4. 기관 이용자의 현황_5등급", "4. 기관 이용자의 현황_인지지원등급", "4. 기관 이용자의 현황_등급외", "4. 기관 이용자의 현황_없음", "4. 기관 이용자의 현황_남", "4. 기관 이용자의 현황_여", "4. 기관 이용자의 현황_치매", "4. 기관 이용자의 현황_치매아님", "5. 직원 수(방문요양_시설장)", "5. 직원 수(방문목욕_시설장)", "5. 직원 수(방문간호_시설장)", "5. 직원 수(방문요양_사회복지사)", "5. 직원 수(방문요양_사회복지사_월 60시간 미만)", "5. 직원 수(방문간호_간호사)", "5. 직원 수(방문간호_간호사_월 60시간 미만)", "5. 직원 수(방문간호_간호조무사)", "5. 직원 수(방문간호_간호조무사_월 60시간 미만)", "5. 직원 수(방문요양_요양보호사)", "5. 직원 수(방문목욕_요양보호사)", "5. 직원 수(방문요양_요양보호사_월 60시간 미만)"
                   , "5. 직원 수(방문목욕_요양보호사_월 60시간 미만)", "5. 직원 수(방문간호_치위생사)", "5. 직원 수(방문간호_치위생사_월 60시간 미만)", "5. 직원 수(방문요양_기타)", "5. 직원 수(방문목욕_기타)", "5. 직원 수(방문간호_기타)", "5. 직원 수(방문요양_기타_월 60시간 미만)", "5. 직원 수(방문목욕_기타_월 60시간 미만)", "5. 직원 수(방문간호_기타_월 60시간 미만)", "5. 직원 수(방문요양_합계)", "5. 직원 수(방문목욕_합계)", "5. 직원 수(방문간호_합계)", "5. 직원 수(방문요양_합계_월 60시간 미만)", "5. 직원 수(방문목욕_합계_월 60시간 미만)", "5. 직원 수(방문간호_합계_월 60시간 미만)", "5. 직원 수(방문요양_기관내 겸직 실인원)", "5. 직원 수(방문목욕_기관내 겸직 실인원)", "5. 직원 수(방문간호_기관내 겸직 실인원)", "6. 직원 수(노인요양공동생활가정_시설장)", "6. 직원 수(노인요양시설_시설장)"
                   , "6. 직원 수(주야간보호_시설장)", "6. 직원 수(단기보호_시설장)", "6. 직원 수(노인요양공동생활가정_사무국장)", "6. 직원 수(노인요양시설_사무국장)", "6. 직원 수(노인요양공동생활가정_사무국장_월 160시간 미만)", "6. 직원 수(노인요양시설_사무국장_월 160시간 미만)", "6. 직원 수(노인요양공동생활가정_사회복지사)", "6. 직원 수(노인요양시설_사회복지사)", "6. 직원 수(주야간보호_사회복지사)", "6. 직원 수(단기보호_사회복지사)", "6. 직원 수(노인요양공동생활가정_사회복지사_월 160시간 미만)", "6. 직원 수(노인요양시설_사회복지사_월 160시간 미만)", "6. 직원 수(주야간보호_사회복지사_월 160시간 미만)", "6. 직원 수(단기보호_사회복지사_월 160시간 미만)", "6. 직원 수(노인요양공동생활가정_간호사)", "6. 직원 수(노인요양시설_간호사)", "6. 직원 수(주야간보호_간호사)", "6. 직원 수(단기보호_간호사)", "6. 직원 수(노인요양공동생활가정_간호사_월 160시간 미만)", "6. 직원 수(노인요양시설_간호사_월 160시간 미만)"
                   , "6. 직원 수(주야간보호_간호사_월 160시간 미만)", "6. 직원 수(단기보호_간호사_월 160시간 미만)", "6. 직원 수(노인요양공동생활가정_간호조무사)", "6. 직원 수(노인요양시설_간호조무사)", "6. 직원 수(주야간보호_간호조무사)", "6. 직원 수(단기보호_간호조무사)", "6. 직원 수(노인요양공동생활가정_간호조무사_월 160시간 미만)", "6. 직원 수(노인요양시설_간호조무사_월 160시간 미만)", "6. 직원 수(주야간보호_간호조무사_월 160시간 미만)", "6. 직원 수(단기보호_간호조무사_월 160시간 미만)", "6. 직원 수(노인요양공동생활가정_물리치료사)", "6. 직원 수(노인요양시설_물리치료사)", "6. 직원 수(주야간보호_물리치료사)", "6. 직원 수(단기보호_물리치료사)", "6. 직원 수(노인요양공동생활가정_물리치료사_월 160시간 미만)", "6. 직원 수(노인요양시설_물리치료사_월 160시간 미만)", "6. 직원 수(주야간보호_물리치료사_월 160시간 미만)", "6. 직원 수(단기보호_물리치료사_월 160시간 미만)", "6. 직원 수(노인요양공동생활가정_작업치료사)", "6. 직원 수(노인요양시설_작업치료사)"
                   , "6. 직원 수(주야간보호_작업치료사)", "6. 직원 수(단기보호_작업치료사)", "6. 직원 수(노인요양공동생활가정_작업치료사_월 160시간 미만)", "6. 직원 수(노인요양시설_작업치료사_월 160시간 미만)", "6. 직원 수(주야간보호_작업치료사_월 160시간 미만)", "6. 직원 수(단기보호_작업치료사_월 160시간 미만)", "6. 직원 수(노인요양공동생활가정_요양보호사)", "6. 직원 수(노인요양시설_요양보호사)", "6. 직원 수(주야간보호_요양보호사)", "6. 직원 수(단기보호_요양보호사)", "6. 직원 수(노인요양공동생활가정_요양보호사_월 160시간 미만)", "6. 직원 수(노인요양시설_요양보호사_월 160시간 미만)", "6. 직원 수(주야간보호_요양보호사_월 160시간 미만)", "6. 직원 수(단기보호_요양보호사_월 160시간 미만)", "6. 직원 수(노인요양시설_사무원)", "6. 직원 수(주야간보호_사무원)", "6. 직원 수(노인요양시설_사무원_월 160시간 미만)", "6. 직원 수(주야간보호_사무원_월 160시간 미만)", "6. 직원 수(노인요양시설_영양사)", "6. 직원 수(노인요양시설_영양사_월 160시간 미만)"
                   , "6. 직원 수(노인요양시설_조리원)", "6. 직원 수(주야간보호_조리원)", "6. 직원 수(단기보호_조리원)", "6. 직원 수(노인요양시설_조리원_월 160시간 미만)", "6. 직원 수(주야간보호_조리원_월 160시간 미만)", "6. 직원 수(단기보호_조리원_월 160시간 미만)", "6. 직원 수(노인요양시설_위생원)", "6. 직원 수(노인요양시설_위생원_월 160시간 미만)", "6. 직원 수(노인요양시설_관리인)", "6. 직원 수(노인요양시설_관리인_월 160시간 미만)", "6. 직원 수(주야간보호_보조원)", "6. 직원 수(주야간보호_보조원_월 160시간 미만)", "6. 직원 수(노인요양공동생활가정_기타)", "6. 직원 수(노인요양시설_기타)", "6. 직원 수(주야간보호_기타)", "6. 직원 수(단기보호_기타)", "6. 직원 수(노인요양공동생활가정_기타_월 160시간 미만)", "6. 직원 수(노인요양시설_기타_월 160시간 미만)", "6. 직원 수(주야간보호_기타_월 160시간 미만)", "6. 직원 수(단기보호_기타_월 160시간 미만)"
                   , "6. 직원 수(노인요양공동생활가정_합계)", "6. 직원 수(노인요양시설_합계)", "6. 직원 수(주야간보호_합계)", "6. 직원 수(단기보호_합계)", "6. 직원 수(노인요양공동생활가정_합계_월 160시간 미만)", "6. 직원 수(노인요양시설_합계_월 160시간 미만)", "6. 직원 수(주야간보호_합계_월 160시간 미만)", "6. 직원 수(단기보호_합계_월 160시간 미만)", "6. 직원 수(노인요양공동생활가정_기관내 겸직 실인원)", "6. 직원 수(노인요양시설_기관내 겸직 실인원)", "6. 직원 수(주야간보호_기관내 겸직 실인원)", "6. 직원 수(단기보호_기관내 겸직 실인원)", "8. 요양보호사 1명이 담당하기 적절한 수급자 수(주간)", "8. 요양보호사 1명이 담당하기 적절한 수급자 수(야간)", "11. 지난 6개월 퇴사 및 입사 현황(사회복지사_퇴사)", "11. 지난 6개월 퇴사 및 입사 현황(사회복지사_입사)", "11. 지난 6개월 퇴사 및 입사 현황(간호사_퇴사)", "11. 지난 6개월 퇴사 및 입사 현황(간호사_입사)", "11. 지난 6개월 퇴사 및 입사 현황(간호조무사_퇴사)", "11. 지난 6개월 퇴사 및 입사 현황(간호조무사_입사)"
                   , "11. 지난 6개월 퇴사 및 입사 현황(물리치료사_퇴사)", "11. 지난 6개월 퇴사 및 입사 현황(물리치료사_입사)", "11. 지난 6개월 퇴사 및 입사 현황(작업치료사_퇴사)", "11. 지난 6개월 퇴사 및 입사 현황(작업치료사_입사)", "11. 지난 6개월 퇴사 및 입사 현황(요양보호사_퇴사)", "11. 지난 6개월 퇴사 및 입사 현황(요양보호사_입사)", "11. 지난 6개월 퇴사 및 입사 현황(사무원_퇴사)", "11. 지난 6개월 퇴사 및 입사 현황(사무원_입사)", "11. 지난 6개월 퇴사 및 입사 현황(조리원_퇴사)", "11. 지난 6개월 퇴사 및 입사 현황(조리원_입사)", "11. 지난 6개월 퇴사 및 입사 현황(위생원_퇴사)", "11. 지난 6개월 퇴사 및 입사 현황(위생원_입사)", "11. 지난 6개월 퇴사 및 입사 현황(기타_퇴사)", "11. 지난 6개월 퇴사 및 입사 현황(기타_입사)", "12. 장기요양인력에 대한 교육 필요성", "12-1. 교육이 필요한 직종(1순위)", "12-1. 교육이 필요한 직종(2순위)", "13. 현재 장기요양요원의 교육에 개선이 필요한 부분(1순위)", "13. 현재 장기요양요원의 교육에 개선이 필요한 부분(2순위)", "14. 치매전담실/ 치매전담형 노인공동생활가정 운영 여부"
                   , "14-1. 치매전담실 현황(치매전담실_개수)", "14-1. 치매전담실 현황(치매전담실_정원)", "14-1. 치매전담실 현황(치매전담실_현원)", "14-1. 치매전담실 현황(치매전담형 노인요양공동생활가정_개수)", "14-1. 치매전담실 현황(치매전담형 노인요양공동생활가정_정원)", "14-1. 치매전담실 현황(치매전담형 노인요양공동생활가정_현원)", "14-2.운영하지 않는 이유", "14-3. 향후 운영 계획", "15. 지난 1년 동안 수급자의 안전사고 유무", "15. 지난 1년 동안 수급자의 안전사고 총 건수", "15-1. 해당하는 안전사고 항목 건수(낙상)", "15-1. 해당하는 안전사고 항목 건수(교통사고)", "15-1. 해당하는 안전사고 항목 건수(질식)", "15-1. 해당하는 안전사고 항목 건수(흡인성 폐렴)", "15-1. 해당하는 안전사고 항목 건수(감염성 질환)", "15-1. 해당하는 안전사고 항목 건수(식중독)", "15-1. 해당하는 안전사고 항목 건수(노인학대 신고)", "15-1. 해당하는 안전사고 항목 건수(기타)", "16. 지난 1년 동안 수급자의 상해나 사고로 손해배상 여부", "16. 지난 1년 동안 수급자의 상해나 사고로 손해배상 총 건수"
                   , "16-1. 대응 방법 건수(전문인배상책임보험으로 처리)", "16-1. 대응 방법 건수(장기요양기관 예산으로 처리)", "16-1. 대응 방법 건수(시설장 개인비용으로 처리)", "16-1. 대응 방법 건수(추가 가입한 민간보험으로 처리)", "16-1. 대응 방법 건수(기타)", "17. 지난 1년 동안 직원이 업무 상 질병 상해 여부", "17. 지난 1년 동안 직원이 업무 상 질병 상해 총 건수", "17-1. 대응 방법 건수(산재보험으로 처리)", "17-1. 대응 방법 건수(장기요양기관 예산으로 처리)", "17-1. 대응 방법 건수(직원 개인비용으로 처리)", "17-1. 대응 방법 건수(추가 가입한 민간보험으로 처리)", "17-1. 대응 방법 건수(장기요양기관 예산 및 직원 개인비용으로 처리)", "17-1. 대응 방법 건수(기타)", "18. 기관 운영의 어려움 정도(인력 채용 및 관리)", "18. 기관 운영의 어려움 정도(수급자 상담 및 사례관리)", "18. 기관 운영의 어려움 정도(보호자 상담 및 대응)", "18. 기관 운영의 어려움 정도(장기요양기관 재정 운영)", "18. 기관 운영의 어려움 정도(급여비용 청구업무)", "18. 기관 운영의 어려움 정도(재무회계 관리업무)", "18. 기관 운영의 어려움 정도(장기요양보험정책 변화에 대응)"
                   , "18. 기관 운영의 어려움 정도(장기요양기관 평가)", "18. 기관 운영의 어려움 정도(안전설비 및 시설관리)", "18. 기관 운영의 어려움 정도(수급자 모집)", "18-1. 수급자 모집이 어려운 이유(1순위)", "18-1. 수급자 모집이 어려운 이유(2순위)", "19. 기관의 건물이 장기요양급여 제공 위한 용도인지 여부", "19-1. 사용하고 있는 건물 형태", "20. 같은 대지 안에 노인요양시설 사용 건물 수", "21. 건물1_전체 층수", "21. 건물1_노인요양시설 사용 층수(최저)", "21. 건물1_노인요양시설 사용 층수(최고)", "21. 건물1_침상이동 엘리베이터 설치여부", "21. 건물2_전체 층수", "21. 건물2_노인요양시설 사용 층수(최저)", "21. 건물2_노인요양시설 사용 층수(최고)", "21. 건물2_침상이동 엘리베이터 설치여부", "21. 건물3_전체 층수", "21. 건물3_노인요양시설 사용 층수(최저)", "21. 건물3_노인요양시설 사용 층수(최고)", "21. 건물3_침상이동 엘리베이터 설치여부"
                   , "21. 건물4_전체 층수", "21. 건물4_노인요양시설 사용 층수(최저)", "21. 건물4_노인요양시설 사용 층수(최고)", "21. 건물4_침상이동 엘리베이터 설치여부", "21. 건물5_전체 층수", "21. 건물5_노인요양시설 사용 층수(최저)", "21. 건물5_노인요양시설 사용 층수(최고)", "21. 건물5_침상이동 엘리베이터 설치여부", "22. 침실개수(1인실)", "22. 침실개수(2인실)", "22. 침실개수(3인실)", "22. 침실개수(4인실)", "22. 사용 입소자 수(1인실)", "22. 사용 입소자 수(2인실)", "22. 사용 입소자 수(3인실)", "22. 사용 입소자 수(4인실)", "24. 지난 6개월 동안 요양보호사 근무형태", "25.지난 1개월 동안 야간근무 운영 형태", "26. 지난 1개월 동안 하루 평균 야간근무 직원 수", "27.요양보호사 외 직종의 야간근무 여부"
                   , "27-1. 지난 1개월 동안 주당 야간 근무 일수(시설장)", "27-1. 지난 1개월 동안 주당 야간 근무 일수(사무국장)", "27-1. 지난 1개월 동안 주당 야간 근무 일수(사회복지사)", "27-1. 지난 1개월 동안 주당 야간 근무 일수(간호(조무)사)", "27-1. 지난 1개월 동안 주당 야간 근무 일수(기타)", "28. 지난 3개월 기관의 비공식 인력 현황(개인 자원봉사자_수)", "28. 지난 3개월 기관의 비공식 인력 현황(개인 자원봉사자_활동횟수)", "28. 지난 3개월 기관의 비공식 인력 현황(자원봉사단체_수)", "28. 지난 3개월 기관의 비공식 인력 현황(자원봉사단체_활동횟수)", "28. 지난 3개월 기관의 비공식 인력 현황(실습생_수)", "28. 지난 3개월 기관의 비공식 인력 현황(실습생_활동횟수)", "28. 지난 3개월 기관의 비공식 인력 현황(사회복무요원_수)", "28. 지난 3개월 기관의 비공식 인력 현황(사회복무요원_활동횟수)", "28. 지난 3개월 기관의 비공식 인력 현황(유급프로그램 강사_수)", "28. 지난 3개월 기관의 비공식 인력 현황(유급프로그램 강사_활동횟수)", "28. 지난 3개월 기관의 비공식 인력 현황(기타_수)", "28. 지난 3개월 기관의 비공식 인력 현황(기타_활동횟수)", "29. 비급여 항목 제공 여부(식사재료비)", "29. 비급여 항목 제공 여부(간식비)", "29. 비급여 항목 제공 여부(경관유동식)"
                   , "29. 비급여 항목 제공 여부(1인실)", "29. 비급여 항목 제공 여부(2인실)", "29. 비급여 항목 제공 여부(이미용비)", "29. 비급여 항목 제공 여부(기타)", "30. 성별", "31. 연령", "33. 보유 자격증_1", "33. 보유 자격증_2", "33. 보유 자격증_3", "33. 보유 자격증_4", "33. 보유 자격증_5", "33. 보유 자격증_6", "33. 보유 자격증_7", "34. 소속 기관의 시설장으로 근무한 일자(년)", "34. 소속 기관의 시설장으로 근무한 일자(월)", "35. 장기요양기관에서 근무한 총 기간(년)", "35. 장기요양기관에서 근무한 총 기간(개월)", "가중치")


write_csv(mdis, "~/Google/R_Jaesol/보육요양 조사자료/요양기관_2019_수정.csv",append=F)